spring.application.name=forohub
spring.datasource.url=jdbc:postgresql://localhost:5432/forohub_db


spring.datasource.username=postgres
spring.datasource.password=26094317

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update