DROP TABLE IF EXISTS topicos;

create table topicos(
    id bigint generated by default as identity,
    titulo varchar(100) not null,
    mensaje varchar(500) not null,
    fecha_creacion timestamp not null,
    status varchar(100) not null,
    autor varchar(100) not null,
    curso varchar(100) not null,
    categoria varchar(100),
    prioridad int,
    etiquetas varchar(200),
    visualizaciones int, --

    primary key(id)
);